### ISSUE TITLE
🐛 Can't use VSCode extension (node not found)

### ISSUE THREAD

**Issue by hyoretsu** [biomejs/biome-vscode#19]
### Environment information

```block
CLI:
  Version:                      1.2.2
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           linux

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v18.15.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "pnpm/8.6.10"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Workspace:
  Open Documents:               0
```

### What happened?

I can run it from the CLI just fine, but the extension throws this error:
```
Configuration file required, looking for one.
Config file found at /home/hyoretsu/@Projects/maple-simulator/biome.json, enabling Biome extension
Using Biome from /home/hyoretsu/@Projects/maple-simulator/node_modules/.bin/biome
[cli] exit 127
[cli-stderr] data 92
[cli-stderr] end
[cli-stdout] end
[Error - 12:33:39 PM] Biome client: couldn't create connection to server.
Error: Command "/home/hyoretsu/@Projects/maple-simulator/node_modules/.bin/biome __print_socket" exited with code 127
Output:
/home/hyoretsu/@Projects/maple-simulator/node_modules/.bin/biome: 16: exec: node: not found

    at getSocket (/home/hyoretsu/.vscode-server/extensions/biomejs.biome-1.4.2-linux-x64/out/main.js:19600:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at createMessageTransports (/home/hyoretsu/.vscode-server/extensions/biomejs.biome-1.4.2-linux-x64/out/main.js:19615:16)
    at LanguageClient2.createConnection (/home/hyoretsu/.vscode-server/extensions/biomejs.biome-1.4.2-linux-x64/out/main.js:15576:28)
    at LanguageClient2.start (/home/hyoretsu/.vscode-server/extensions/biomejs.biome-1.4.2-linux-x64/out/main.js:15152:30)
    at activate (/home/hyoretsu/.vscode-server/extensions/biomejs.biome-1.4.2-linux-x64/out/main.js:19421:3)
    at p.n (/home/hyoretsu/.vscode-server/bin/6c3e3dba23e8fadc360aed75ce363ba185c49794/out/vs/workbench/api/node/extensionHostProcess.js:103:6206)
    at p.m (/home/hyoretsu/.vscode-server/bin/6c3e3dba23e8fadc360aed75ce363ba185c49794/out/vs/workbench/api/node/extensionHostProcess.js:103:6169)
    at p.l (/home/hyoretsu/.vscode-server/bin/6c3e3dba23e8fadc360aed75ce363ba185c49794/out/vs/workbench/api/node/extensionHostProcess.js:103:5626)
[cli-stdout] close
[cli] close 127
[cli-stderr] close
```

### Expected result

It should work just fine.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by nhedger** [comment]
I believe this issue has been fixed in a previous release of the extension.

I'll close the issue to keep the repo tidy, but feel free to reopen it if you reencounter it.

Thanks!
