### ISSUE TITLE
🐛 Latest version keeps crashing

### ISSUE THREAD

**Issue by angel-luis** [biomejs/biome-vscode#209]
### VS Code version

1.88.1

### Extension version

2.2.2

### Biome version

1.7.2

### Operating system

- [ ] Windows
- [X] macOS
- [ ] Linux

### Description

The extension stops to work after some minutes.
<img width="465" alt="image" src="https://github.com/biomejs/biome-vscode/assets/17672548/90a1968b-041a-483b-8d27-e06da778667a">

### Steps to reproduce

I've upgraded and also tried to reinstall the extension

### Expected behavior

Don't crash

### Does this issue occur when using the CLI directly?

Not sure / Not applicable

### Logs

```plain text
Connecting to "/Users/angelluis/Library/Caches/dev.biomejs.biome/biome-socket-1.7.2" ...
[Info  - 17:35:11] Server initialized with PID: 70417
[Error - 17:50:25] Client Biome: connection to server is erroring. Shutting down server.
[Error - 17:50:25] Client Biome: connection to server is erroring. Shutting down server.
[Error - 17:50:25] Sending document notification textDocument/didOpen failed.
Error: write EPIPE
	at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)
[Error - 17:50:25] Stopping server failed
  Message: This socket has been ended by the other party
  Code: -32099 
[Error - 17:50:25] Stopping server failed
  Message: This socket has been ended by the other party
  Code: -32099 
[Error - 17:50:25] Stopping server failed
  Message: This socket has been ended by the other party
  Code: -32099
```

**Comment by vbasky** [comment]
I have the same issue too.

`[cli]exit 0
Connecting to "/Users/vikram/Library/Caches/dev.biomejs.biome/biome-socket-1.7.2" ...
[cli-stderr] data 395
[Error - 09:28:49] Client Biome: connection to server is erroring. Shutting down server.
[Error - 09:28:49] Client Biome: connection to server is erroring. Shutting down server.
[Error - 09:28:49] Sending document notification textDocument/didOpen failed
Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)
[cli-stdout] end
[cli-stdout] finish
[Error - 09:28:49] Sending document notification textDocument/didOpen failed
Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (node:net:569:14)
    at /Users/vikram/.vscode/extensions/biomejs.biome-2.2.2/out/main.js:3023:25
    at new Promise (<anonymous>)
    at WritableStreamWrapper.write (/Users/vikram/.vscode/extensions/biomejs.biome-2.2.2/out/main.js:3014:16)
    at StreamMessageWriter.doWrite (/Users/vikram/.vscode/extensions/biomejs.biome-2.2.2/out/main.js:1442:31)
    at /Users/vikram/.vscode/extensions/biomejs.biome-2.2.2/out/main.js:1433:25
    at runNextTicks (node:internal/process/task_queues:60:5)
    at processImmediate (node:internal/timers:447:9)
[cli-stdout] close
[Error - 09:28:49] Connection to server got closed. Server will not be restarted.
[cli-stderr] end
[cli-stderr] finish
[cli] close 0
[cli-stderr] close
[Error - 09:28:49] Stopping server failed
  Message: This socket has been ended by the other party
  Code: -32099 
[Error - 09:28:49] Stopping server failed
  Message: This socket has been ended by the other party
  Code: -32099 
[Error - 09:28:49] Stopping server failed
  Message: This socket has been ended by the other party
  Code: -32099 
`
