### ISSUE TITLE
🐛 Biome client: couldn't create connection to server

### ISSUE THREAD

**Issue by stianberg** [biomejs/biome-vscode#219]
### VS Code version

1.89.1

### Extension version

2.2.2

### Biome version

1.7.3

### Operating system

- [X] Windows
- [ ] macOS
- [ ] Linux

### Description

Getting an error in VS Code saying "Biome client: couldn't create connection to server."

The exception:
```
[Error - 11:25:09 AM] Biome client: couldn't create connection to server.
Error: Command "c:\Users\stian.berg\AppData\Roaming\Code\User\workspaceStorage\326c904ecce485a74a3b80bc6d005353\biomejs.biome\biome.exe __print_socket" exited with code 3221225781
	at getSocket (c:\Users\stian.berg\.vscode\extensions\biomejs.biome-2.2.2\out\main.js:36605:11)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async createMessageTransports (c:\Users\stian.berg\.vscode\extensions\biomejs.biome-2.2.2\out\main.js:36619:16)
	at async LanguageClient2.createConnection (c:\Users\stian.berg\.vscode\extensions\biomejs.biome-2.2.2\out\main.js:15598:28)
	at async LanguageClient2.start (c:\Users\stian.berg\.vscode\extensions\biomejs.biome-2.2.2\out\main.js:15174:30)
	at async activate (c:\Users\stian.berg\.vscode\extensions\biomejs.biome-2.2.2\out\main.js:36368:3)
	at async h.n (c:\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:143:6281)
	at async h.m (c:\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:143:6244)
	at async h.l (c:\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:143:5701)
```

Restarting the LSP server doesn't work.

If try to run biome.exe I get this error:
`biome.exe: error while loading shared libraries: api-ms-win-crt-heap-l1-1-0.dll: cannot open shared object file`

### Steps to reproduce

1. yarn install
2. install VS extension
3. open a tsx file

### Expected behavior

Expect Biome to start

### Does this issue occur when using the CLI directly?

Not sure / Not applicable

### Logs

```plain text
Biome trace is empty
```

**Comment by stianberg** [comment]
Installed `VISUAL C++ REDISTRIBUTABLE FOR VISUAL STUDIO 2019` and restarted PC and it's now working.
