### ISSUE TITLE
🐛 `Biome encountered a fatal error`

### ISSUE THREAD

**Issue by hamirmahal** [biomejs/biome-vscode#284]
### VS Code version

1.91.1

### Extension version

2.3.0

### Biome version

1.8.3

### Operating system

- [ ] Windows
- [ ] macOS
- [X] Linux

### Description

`Biome encountered a fatal error`.

![image](https://github.com/user-attachments/assets/5625e3aa-0d09-45d4-811a-d643bd701b8a)

### Steps to reproduce

1. Switch between different commits.
2. Click on Biome in the status bar.
3. Select `1.8.3` as the version.

### Expected behavior

Biome runs without issue.

### Does this issue occur when using the CLI directly?

Not sure / Not applicable

### Logs

```plain text
`Biome Trace` is empty.
```

**Comment by hamirmahal** [comment]
![image](https://github.com/user-attachments/assets/cda2b0da-40e4-4ab5-b5c4-a3352f51b020)

**Comment by hamirmahal** [comment]
<details>
<summary>VSCode Biome Output</summary>
<br>

```
Searching for Biome in PATH
Biome binary found at /home/hamir/.config/Code/User/globalStorage/biomejs.biome/server/biome
Executing Biome from: /home/hamir/.config/Code/User/globalStorage/biomejs.biome/server/biome
[cli-stdout] data 44
[cli] exit 0
Connecting to "/home/hamir/.cache/biome/biome-socket-1.8.3" ...
[Info  - 1:03:59 PM] Server initialized with PID: 6244
Reloading biome executable.
Biome binary found at /home/hamir/.config/Code/User/globalStorage/biomejs.biome/server/biome
Executing Biome from: /home/hamir/.config/Code/User/globalStorage/biomejs.biome/server/biome
[cli-stdout] data 44
[cli-stdout] end
[cli-stdout] finish
[cli-stderr] end
[cli-stderr] finish
[cli] exit 0
Connecting to "/home/hamir/.cache/biome/biome-socket-1.8.3" ...
[cli-stderr] close
[cli] close 0
[cli-stdout] close
[Info  - 7:50:25 PM] Server initialized with PID: 6244
Reloading biome executable.
Biome binary found at /home/hamir/.config/Code/User/globalStorage/biomejs.biome/server/biome
Executing Biome from: /home/hamir/.config/Code/User/globalStorage/biomejs.biome/server/biome
[cli-stdout] data 44
[cli-stderr] end
[cli-stderr] finish
[cli-stdout] end
[cli-stdout] finish
[cli] exit 0
Connecting to "/home/hamir/.cache/biome/biome-socket-1.8.3" ...
[cli-stdout] close
[cli] close 0
[cli-stderr] close
[Info  - 7:50:35 PM] Server initialized with PID: 6244
Reloading biome executable.
Biome binary found at /home/hamir/.config/Code/User/globalStorage/biomejs.biome/server/biome
Executing Biome from: /home/hamir/.config/Code/User/globalStorage/biomejs.biome/server/biome
[cli-stdout] data 44
[cli-stdout] end
[cli-stdout] finish
[cli-stderr] end
[cli-stderr] finish
[cli] exit 0
Connecting to "/home/hamir/.cache/biome/biome-socket-1.8.3" ...
[cli-stderr] close
[cli] close 0
[cli-stdout] close
[Info  - 7:50:56 PM] Server initialized with PID: 6244
Reloading biome executable.
Biome binary found at /home/hamir/.config/Code/User/globalStorage/biomejs.biome/server/biome
Executing Biome from: /home/hamir/.config/Code/User/globalStorage/biomejs.biome/server/biome
[cli-stdout] data 44
[cli-stderr] end
[cli-stderr] finish
[cli-stderr] close
[cli-stdout] end
[cli-stdout] finish
[cli-stdout] close
[cli] exit 0
[cli] close 0
Connecting to "/home/hamir/.cache/biome/biome-socket-1.8.3" ...
[Info  - 7:52:49 PM] Server initialized with PID: 6244
[Error - 8:19:06 PM] Request textDocument/codeAction failed.
  Message: failed to access range Range { start: Position { line: 327, character: 15 }, end: Position { line: 327, character: 27 } } in document file:///home/hamir/redacted/app/src/app/%5Borg%5D/%28app%29/settings/users/page.tsx LineIndex { newlines: [0, 14, 15, 58, 115, 124, 134, 144, 165, 173, 182, 192, 207, 226, 236, 245, 269, 317, 331, 341, 356, 374, 402, 430, 459, 509, 536, 611, 612, 677, 728, 800, 801, 821, 866, 898, 914, 931, 946, 963, 981, 998, 1016, 1028, 1038, 1046, 1055, 1056, 1079, 1092, 1106, 1119, 1139, 1162, 1183, 1199, 1220, 1244, 1264, 1287, 1301, 1341, 1383, 1408, 1443, 1498, 1548, 1610, 1641, 1692, 1722, 1772, 1778, 1816, 1831, 1879, 1906, 1937, 1990, 2007, 2008, 2047, 2062, 2111, 2138, 2169, 2222, 2239, 2240, 2251, 2290, 2333, 2385, 2401, 2437, 2457, 2504, 2546, 2607, 2622, 2663, 2698, 2709, 2734, 2757, 2793, 2827, 2862, 2882, 2893, 2914, 2948, 2978, 3014, 3056, 3076, 3087, 3108, 3141, 3170, 3205, 3246, 3266, 3286, 3297, 3332, 3350, 3380, 3412, 3432, 3474, 3486, 3508, 3528, 3545, 3560, 3572, 3577, 3579, 3580, 3616, 3661, 3725, 3751, 3814, 3868, 3900, 3916, 3997, 4073, 4147, 4148, 4180, 4190, 4250, 4303, 4324, 4366, 4371, 4372, 4424, 4461, 4462, 4485, 4500, 4540, 4557, 4567, 4610, 4668, 4714, 4724, 4732, 4743, 4765, 4806, 4879, 4887, 4888, 4933, 5008, 5016, 5017, 5068, 5087, 5112, 5189, 5202, 5214, 5222, 5223, 5274, 5293, 5318, 5395, 5408, 5420, 5428, 5435, 5440, 5441, 5461, 5509, 5571, 5577, 5637, 5658, 5659, 5679, 5741, 5751, 5752, 5788, 5834, 5884, 5894, 5924, 5967, 5983, 6011, 6038, 6078, 6103, 6116, 6171, 6181, 6196, 6214, 6229, 6243, 6248, 6249, 6278, 6347, 6358, 6369, 6384, 6405, 6449, 6495, 6527, 6573, 6625, 6673, 6711, 6759, 6813, 6859, 6911, 6922, 6930, 6955, 6979, 6985, 7000, 7014, 7033, 7049, 7062, 7067, 7069], line_wide_chars: {} }
  Code: -32603 
failed to access range Range { start: Position { line: 327, character: 15 }, end: Position { line: 327, character: 27 } } in document file:///home/hamir/redacted/app/src/app/%5Borg%5D/%28app%29/settings/users/page.tsx LineIndex { newlines: [0, 14, 15, 58, 115, 124, 134, 144, 165, 173, 182, 192, 207, 226, 236, 245, 269, 317, 331, 341, 356, 374, 402, 430, 459, 509, 536, 611, 612, 677, 728, 800, 801, 821, 866, 898, 914, 931, 946, 963, 981, 998, 1016, 1028, 1038, 1046, 1055, 1056, 1079, 1092, 1106, 1119, 1139, 1162, 1183, 1199, 1220, 1244, 1264, 1287, 1301, 1341, 1383, 1408, 1443, 1498, 1548, 1610, 1641, 1692, 1722, 1772, 1778, 1816, 1831, 1879, 1906, 1937, 1990, 2007, 2008, 2047, 2062, 2111, 2138, 2169, 2222, 2239, 2240, 2251, 2290, 2333, 2385, 2401, 2437, 2457, 2504, 2546, 2607, 2622, 2663, 2698, 2709, 2734, 2757, 2793, 2827, 2862, 2882, 2893, 2914, 2948, 2978, 3014, 3056, 3076, 3087, 3108, 3141, 3170, 3205, 3246, 3266, 3286, 3297, 3332, 3350, 3380, 3412, 3432, 3474, 3486, 3508, 3528, 3545, 3560, 3572, 3577, 3579, 3580, 3616, 3661, 3725, 3751, 3814, 3868, 3900, 3916, 3997, 4073, 4147, 4148, 4180, 4190, 4250, 4303, 4324, 4366, 4371, 4372, 4424, 4461, 4462, 4485, 4500, 4540, 4557, 4567, 4610, 4668, 4714, 4724, 4732, 4743, 4765, 4806, 4879, 4887, 4888, 4933, 5008, 5016, 5017, 5068, 5087, 5112, 5189, 5202, 5214, 5222, 5223, 5274, 5293, 5318, 5395, 5408, 5420, 5428, 5435, 5440, 5441, 5461, 5509, 5571, 5577, 5637, 5658, 5659, 5679, 5741, 5751, 5752, 5788, 5834, 5884, 5894, 5924, 5967, 5983, 6011, 6038, 6078, 6103, 6116, 6171, 6181, 6196, 6214, 6229, 6243, 6248, 6249, 6278, 6347, 6358, 6369, 6384, 6405, 6449, 6495, 6527, 6573, 6625, 6673, 6711, 6759, 6813, 6859, 6911, 6922, 6930, 6955, 6979, 6985, 7000, 7014, 7033, 7049, 7062, 7067, 7069], line_wide_chars: {} }

Caused by:
    position Position { line: 327, character: 15 } is out of range
Reloading biome executable.
Biome binary found at /home/hamir/.config/Code/User/globalStorage/biomejs.biome/server/biome
Executing Biome from: /home/hamir/.config/Code/User/globalStorage/biomejs.biome/server/biome
[cli-stderr] end
[cli-stderr] finish
[cli-stdout] end
[cli-stdout] finish
[cli-stdout] close
[cli] close 0
[cli-stderr] close
[cli-stdout] data 44
[cli] exit 0
Connecting to "/home/hamir/.cache/biome/biome-socket-1.8.3" ...
[Info  - 11:15:12 PM] Server initialized with PID: 80521
Reloading biome executable.
Biome binary found at /home/hamir/.config/Code/User/globalStorage/biomejs.biome/server/biome
Executing Biome from: /home/hamir/.config/Code/User/globalStorage/biomejs.biome/server/biome
[cli-stdout] data 44
[cli-stdout] end
[cli-stdout] finish
[cli-stderr] end
[cli-stderr] finish
[cli] exit 0
Connecting to "/home/hamir/.cache/biome/biome-socket-1.8.3" ...
[Error - 11:15:23 PM] Biome client: couldn't create connection to server.
Error: connect ECONNREFUSED /home/hamir/.cache/biome/biome-socket-1.8.3
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)
Reloading client failed: Error: Could not connect to the Biome server at "/home/hamir/.cache/biome/biome-socket-1.8.3": connect ECONNREFUSED /home/hamir/.cache/biome/biome-socket-1.8.3
[cli-stderr] close
[cli] close 0
[cli-stdout] close
[cli-stderr] end
[cli-stderr] finish
[cli-stdout] end
[cli-stdout] finish
[cli-stdout] close
[cli] close 0
[cli-stderr] close
[Error - 11:58:39 PM] Stopping client failed
Error: Client is not running and can't be stopped. It's current state is: startFailed
    at LanguageClient2.shutdown (/home/hamir/.vscode/extensions/biomejs.biome-2.3.0/out/main.js:15374:17)
    at LanguageClient2.stop (/home/hamir/.vscode/extensions/biomejs.biome-2.3.0/out/main.js:15351:21)
    at LanguageClient2.stop (/home/hamir/.vscode/extensions/biomejs.biome-2.3.0/out/main.js:17856:22)
    at /home/hamir/.vscode/extensions/biomejs.biome-2.3.0/out/main.js:36118:20
    at f.h (/snap/code/164/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:154:204400)
    at f.g (/snap/code/164/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:154:203392)
    at f.executeCommand (/snap/code/164/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:154:203299)
    at Object.executeCommand (/snap/code/164/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:164:23051)
    at /home/hamir/.vscode/extensions/biomejs.biome-2.3.0/out/main.js:35850:37
    at R.d (/snap/code/164/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:154:170820)
    at R.withProgress (/snap/code/164/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:154:170683)
    at Object.withProgress (/snap/code/164/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:164:34458)
    at selectAndDownload (/home/hamir/.vscode/extensions/biomejs.biome-2.3.0/out/main.js:35843:38)
    at /home/hamir/.vscode/extensions/biomejs.biome-2.3.0/out/main.js:36275:5
    at f.h (/snap/code/164/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:154:204392)
[Error - 11:58:41 PM] Restarting client failed
Error: connect ECONNREFUSED /home/hamir/.cache/biome/biome-socket-1.8.3
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)
[Error - 11:58:55 PM] Restarting client failed
Error: connect ECONNREFUSED /home/hamir/.cache/biome/biome-socket-1.8.3
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)
[Error - 12:13:44 AM] Stopping client failed
Error: Client is not running and can't be stopped. It's current state is: startFailed
    at LanguageClient2.shutdown (/home/hamir/.vscode/extensions/biomejs.biome-2.3.0/out/main.js:15374:17)
    at LanguageClient2.stop (/home/hamir/.vscode/extensions/biomejs.biome-2.3.0/out/main.js:15351:21)
    at LanguageClient2.stop (/home/hamir/.vscode/extensions/biomejs.biome-2.3.0/out/main.js:17856:22)
    at /home/hamir/.vscode/extensions/biomejs.biome-2.3.0/out/main.js:36118:20
    at f.h (/snap/code/164/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:154:204400)
    at f.g (/snap/code/164/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:154:203392)
    at f.executeCommand (/snap/code/164/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:154:203299)
    at Object.executeCommand (/snap/code/164/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:164:23051)
    at /home/hamir/.vscode/extensions/biomejs.biome-2.3.0/out/main.js:35850:37
    at R.d (/snap/code/164/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:154:170820)
    at R.withProgress (/snap/code/164/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:154:170683)
    at Object.withProgress (/snap/code/164/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:164:34458)
    at selectAndDownload (/home/hamir/.vscode/extensions/biomejs.biome-2.3.0/out/main.js:35843:38)
    at /home/hamir/.vscode/extensions/biomejs.biome-2.3.0/out/main.js:36275:5
    at f.h (/snap/code/164/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:154:204392)
[Error - 12:13:46 AM] Restarting client failed
Error: connect ECONNREFUSED /home/hamir/.cache/biome/biome-socket-1.8.3
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)
[Error - 12:16:39 AM] Stopping client failed
Error: Client is not running and can't be stopped. It's current state is: startFailed
    at LanguageClient2.shutdown (/home/hamir/.vscode/extensions/biomejs.biome-2.3.0/out/main.js:15374:17)
    at LanguageClient2.stop (/home/hamir/.vscode/extensions/biomejs.biome-2.3.0/out/main.js:15351:21)
    at LanguageClient2.stop (/home/hamir/.vscode/extensions/biomejs.biome-2.3.0/out/main.js:17856:22)
    at /home/hamir/.vscode/extensions/biomejs.biome-2.3.0/out/main.js:36118:20
    at f.h (/snap/code/164/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:154:204400)
    at f.g (/snap/code/164/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:154:203392)
    at f.executeCommand (/snap/code/164/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:154:203299)
    at Object.executeCommand (/snap/code/164/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:164:23051)
    at /home/hamir/.vscode/extensions/biomejs.biome-2.3.0/out/main.js:35850:37
    at R.d (/snap/code/164/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:154:170820)
    at R.withProgress (/snap/code/164/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:154:170683)
    at Object.withProgress (/snap/code/164/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:164:34458)
    at selectAndDownload (/home/hamir/.vscode/extensions/biomejs.biome-2.3.0/out/main.js:35843:38)
    at /home/hamir/.vscode/extensions/biomejs.biome-2.3.0/out/main.js:36275:5
    at f.h (/snap/code/164/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:154:204392)
[Error - 12:16:41 AM] Restarting client failed
Error: connect ECONNREFUSED /home/hamir/.cache/biome/biome-socket-1.8.3
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)
[Error - 12:17:02 AM] Stopping client failed
Error: Client is not running and can't be stopped. It's current state is: startFailed
    at LanguageClient2.shutdown (/home/hamir/.vscode/extensions/biomejs.biome-2.3.0/out/main.js:15374:17)
    at LanguageClient2.stop (/home/hamir/.vscode/extensions/biomejs.biome-2.3.0/out/main.js:15351:21)
    at LanguageClient2.stop (/home/hamir/.vscode/extensions/biomejs.biome-2.3.0/out/main.js:17856:22)
    at /home/hamir/.vscode/extensions/biomejs.biome-2.3.0/out/main.js:36118:20
    at f.h (/snap/code/164/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:154:204400)
    at f.g (/snap/code/164/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:154:203392)
    at f.executeCommand (/snap/code/164/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:154:203299)
    at Object.executeCommand (/snap/code/164/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:164:23051)
    at /home/hamir/.vscode/extensions/biomejs.biome-2.3.0/out/main.js:35850:37
    at R.d (/snap/code/164/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:154:170820)
    at R.withProgress (/snap/code/164/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:154:170683)
    at Object.withProgress (/snap/code/164/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:164:34458)
    at selectAndDownload (/home/hamir/.vscode/extensions/biomejs.biome-2.3.0/out/main.js:35843:38)
    at /home/hamir/.vscode/extensions/biomejs.biome-2.3.0/out/main.js:36275:5
    at f.h (/snap/code/164/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:154:204392)
[Error - 12:17:09 AM] Restarting client failed
Error: connect ECONNREFUSED /home/hamir/.cache/biome/biome-socket-1.8.3
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)
```
</details>

**Comment by ematipico** [comment]
Have you tried to restart the LSP? There's a command palette for that `Biome: restart LSP server`

**Comment by hamirmahal** [comment]
I haven't run into the issue again, but I can try that if I do.

**Comment by laogui** [comment]
I encounter this many times, and each time restarting the editor fixes it, but the error reappears after a while

**Comment by RonB** [comment]
Please reopen, this is an issue. I do need to restart lsp often, but it keeps happening, mainly after a vscode session has been open for a longer period of time.

**Comment by ematipico** [comment]
@RonB please open a new issue. This one is two years old, a lot has changed. Don't forget to attach a minimal reproduction
