### ISSUE TITLE
🐛 Error: Command "/home/name/.local/share/pnpm/biome __print_socket" exited with code 0

### ISSUE THREAD

**Issue by reckek** [biomejs/biome-vscode#305]
### VS Code version

1.92.2

### Extension version

2.3.0

### Biome version

0.3.3

### Operating system

- [ ] Windows
- [ ] macOS
- [X] Linux

### Description

Throw error by launch vscode on project

### Steps to reproduce

launch project

### Expected behavior

launch project

### Does this issue occur when using the CLI directly?

Yes

### Logs

```plain text
earching for Biome in PATH
Biome found in PATH: /home/name/.local/share/pnpm/biome
Biome binary found at /home/name/.local/share/pnpm/biome
Executing Biome from: /home/name/.local/share/pnpm/biome
[cli-stderr] end
[cli-stderr] finish
[cli-stdout] end
[cli-stdout] finish
[cli] exit 0
[Error - 2:27:07 PM] Biome client: couldn't create connection to server.
Error: Command "/home/name/.local/share/pnpm/biome __print_socket" exited with code 0
    at getSocket (/home/name/.vscode/extensions/biomejs.biome-2.3.0/out/main.js:36539:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at createMessageTransports (/home/name/.vscode/extensions/biomejs.biome-2.3.0/out/main.js:36553:16)
    at LanguageClient2.createConnection (/home/name/.vscode/extensions/biomejs.biome-2.3.0/out/main.js:15548:28)
    at LanguageClient2.start (/home/name/.vscode/extensions/biomejs.biome-2.3.0/out/main.js:15124:30)
    at activate (/home/name/.vscode/extensions/biomejs.biome-2.3.0/out/main.js:36294:3)
    at m.n (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:144:6409)
    at m (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:144:6372)
    at m.l (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:144:5829)
[cli-stdout] close
[cli] close 0
[cli-stderr] close
```

**Comment by reckek** [comment]
I've fixed it
