### ISSUE TITLE
🐛 Having a single project without Biome in a Workspace crashes the extion

### ISSUE THREAD

**Issue by hyoretsu** [biomejs/biome-vscode#457]
### VS Code version

1.96.2

### Extension version

2024.11.301111

### Biome version

1.9.4

### Operating system

- [ ] Windows
- [ ] macOS
- [ ] Linux

### Description

Projects in a workspace without Biome crash the extension. It's sort of expected on a single project, but quite on a possibly multi-language workspace.

![image](https://github.com/user-attachments/assets/60ca4bf5-38f1-45ad-812e-e16250afd668)

```
internalError/io ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  × Errors occurred while executing I/O operations.
    
    Caused by:
      Access is denied. (os error 5)
```

```
2024-12-26 10:51:21.085 [info] [Error - 10:51:20 AM] Biome language server error
2024-12-26 10:51:21.085 [info] [Error - 10:51:20 AM] Stopping server failed
2024-12-26 10:51:21.085 [info] Error: Client is not running and can't be stopped. It's current state is: starting
    at BiomeLanguageClient.shutdown (c:\Users\hyore\.vscode\extensions\biomejs.biome-2024.12.22126\out\index.js:50368:21)
    at BiomeLanguageClient.stop (c:\Users\hyore\.vscode\extensions\biomejs.biome-2024.12.22126\out\index.js:50339:23)
    at BiomeLanguageClient.stop (c:\Users\hyore\.vscode\extensions\biomejs.biome-2024.12.22126\out\index.js:51249:24)
    at BiomeLanguageClient.handleConnectionError (c:\Users\hyore\.vscode\extensions\biomejs.biome-2024.12.22126\out\index.js:50600:20)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-12-26 10:51:21.085 [info] [Error - 10:51:20 AM] biome client: couldn't create connection to server.
2024-12-26 10:51:21.085 [info]   Message: write EPIPE
  Code: -32099 
2024-12-26 10:51:21.085 [info] error: could not find bin metadata file

Bun failed to remap this bin to its proper location within node_modules.
This is an indication of a corrupted node_modules directory.

Please run 'bun install --force' in the project root and try
it again. If this message persists, please open an issue:
https://github.com/oven-sh/bun/issues


2024-12-26 10:51:21.085 [info] [Error - 10:51:20 AM] Biome language server closed
```

### Steps to reproduce

Create a workspace with multiple projects where one doesn't have Biome either installed or at all.

### Expected behavior

It should work for the projects that do use Biome.

### Does this issue occur when using the CLI directly?

No

### Link to a minimal reproduction

Kinda too big to include, but uninstalling Biome from a project should be enough.

**Comment by nhedger** [comment]
Hey,

Thanks for opening this issue.

According to the error message in your log, woudn't be an issue with your node_modules ?

Anyway, I would be happy to take a look if you could provide a minimal reproduction repository.

**Comment by hyoretsu** [comment]
It isn't a repository, but a VSCode workspace. That's precisely the issue. A single non-Biome project in a workspace crashes the others.

**Comment by dyc3** [comment]
A repo is merely what we typically use to easily replicate end user's file structure. Usually that's enough, but in this case a repo and some instructions on how to configure vscode will suffice. I've personally never used the workspace feature so I have no idea how it works.

**Comment by hyoretsu** [comment]
It's not happening anymore for some reason, so I'm closing it.
